-- =====================================================================
-- THE PET HOUSE - Loja online (pedidos de ração)
-- Rode este arquivo inteiro no Supabase > SQL Editor > New query > Run.
-- É idempotente: pode rodar mais de uma vez sem quebrar nada.
-- Nada aqui altera dados existentes do PDV, só acrescenta.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Campos da loja nos produtos que já existem
-- ---------------------------------------------------------------------
alter table public.products add column if not exists especie          text;
alter table public.products add column if not exists porte            text;
alter table public.products add column if not exists perfil           text;
alter table public.products add column if not exists foto_url         text;
alter table public.products add column if not exists visivel_loja     boolean not null default true;
alter table public.products add column if not exists vende_fracionado boolean not null default true;

comment on column public.products.especie          is 'cao | gato | null (serve os dois)';
comment on column public.products.porte            is 'pequena | media | grande | null (serve todos)';
comment on column public.products.perfil           is 'filhote | adulto | castrado | senior | null';
comment on column public.products.visivel_loja     is 'aparece no catálogo da loja online';
comment on column public.products.vende_fracionado is 'aceita venda por kg na loja online';

-- Preenche a partir do campo "tipo" que o PDV já usa (só onde está vazio)
update public.products set especie = tipo
  where especie is null and tipo in ('cao', 'gato');

update public.products set perfil = tipo
  where perfil is null and tipo in ('filhote', 'castrado');

-- Produto que não é ração não se vende fracionado
update public.products set vende_fracionado = false
  where categoria is not null and categoria <> 'racao';

-- ---------------------------------------------------------------------
-- 2. Pedidos da loja online
-- ---------------------------------------------------------------------
create table if not exists public.orders (
  id               bigint generated by default as identity primary key,
  client_id        bigint references public.clients(id) on delete set null,
  cliente_nome     text        not null,
  cliente_whatsapp text        not null,
  tipo_entrega     text        not null default 'entrega',  -- entrega | retirada
  endereco         text,
  referencia       text,
  janela           text,                                    -- "Hoje, 14h-17h"
  observacao       text,
  subtotal         numeric(10,2) not null default 0,
  frete            numeric(10,2) not null default 0,
  total            numeric(10,2) not null default 0,
  status           text        not null default 'novo',     -- novo | confirmado | separando | pronto | entregue | cancelado
  assinatura       boolean     not null default false,
  frequencia       text,                                    -- semanal | quinzenal | mensal
  sale_id          bigint references public.sales(id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- quantidade_kg segue exatamente a mesma convenção de sale_items do PDV:
--   tipo_venda = 'kg'      -> quilos
--   tipo_venda = 'saco'    -> número de sacos fechados
--   tipo_venda = 'unidade' -> número de unidades
create table if not exists public.order_items (
  id             bigint generated by default as identity primary key,
  order_id       bigint not null references public.orders(id) on delete cascade,
  product_id     bigint references public.products(id) on delete set null,
  descricao      text   not null,
  tipo_venda     text   not null default 'kg',
  quantidade_kg  numeric(10,3) not null default 0,
  preco_unitario numeric(10,4) not null default 0,
  subtotal       numeric(10,2) not null default 0
);

create index if not exists orders_status_idx     on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_whatsapp_idx   on public.orders (cliente_whatsapp);
create index if not exists order_items_order_idx on public.order_items (order_id);

-- ---------------------------------------------------------------------
-- 3. Configurações da loja (usa a tabela settings que já existe)
-- ---------------------------------------------------------------------
insert into public.settings (key, value) values
  ('loja_aberta',         'true'),
  ('whatsapp_loja',       ''),
  ('endereco_loja',       'Rua Bernardo Vasconcelos, 304 - Vila Maria Helena'),
  ('frete_valor',         '9.90'),
  ('frete_gratis_acima',  '99'),
  ('pedido_minimo',       '0')
on conflict (key) do nothing;

-- ---------------------------------------------------------------------
-- 4. Acesso
--
-- Mantém a mesma postura das outras tabelas do projeto: a chave anon
-- (que já está no front e na API) consegue ler e gravar pedidos.
--
-- COMO FECHAR DEPOIS (recomendado quando sobrar tempo): crie a variável
-- SUPABASE_SERVICE_ROLE_KEY na Vercel, faça a API usá-la, e troque as
-- policies abaixo por apenas o INSERT do anon. Aí só o servidor lê
-- pedidos, e ninguém com a chave pública consegue listar os seus.
-- ---------------------------------------------------------------------
alter table public.orders      enable row level security;
alter table public.order_items enable row level security;

drop policy if exists loja_orders_all      on public.orders;
drop policy if exists loja_order_items_all on public.order_items;

create policy loja_orders_all on public.orders
  for all to anon, authenticated using (true) with check (true);

create policy loja_order_items_all on public.order_items
  for all to anon, authenticated using (true) with check (true);
